CREATE TABLE time_metric (
ID INTEGER IDENTITY PRIMARY KEY ,
TEMPERATURE INTEGER NOT NULL,
DATETIME TIMESTAMP
);


CREATE TABLE stadistic_time (
ID INTEGER IDENTITY PRIMARY KEY,
DATE DATE,
TIME VARCHAR(50),
MIN INTEGER NOT NULL,
MAX INTEGER NOT NULL,
AVERAGE DOUBLE
);